#!/usr/bin/env bash
# Set up the nxusKit SDK for a project that uses it as a dependency.
#
# Usage (must source so exports and symlinks apply):
#   source setup-sdk.sh                    # uses ~/.nxuskit/sdk/current
#   source setup-sdk.sh /path/to/sdk-dir   # uses specific SDK directory
#
# What it does:
#   1. Exports NXUSKIT_SDK_DIR, NXUSKIT_LIB_DIR, library paths, CGO flags
#   2. Creates packages/nxuskit symlink -> $NXUSKIT_SDK_DIR/rust
#      (so Rust path deps like path = "../../../../packages/nxuskit" resolve)
#
# Run once per project checkout. The symlink is local (add packages/ to .gitignore).
# Works in both bash and zsh.

set -euo pipefail

# Detect script location (bash + zsh compatible)
_script="${BASH_SOURCE[0]:-${(%):-%x}}"
SCRIPT_DIR="$(cd "$(dirname "$_script")" && pwd)"

# Detect project root: walk up from script location to find .git
_dir="$SCRIPT_DIR"
PROJECT_ROOT=""
while [[ "$_dir" != "/" ]]; do
    if [[ -d "$_dir/.git" ]]; then
        PROJECT_ROOT="$_dir"
        break
    fi
    _dir="$(dirname "$_dir")"
done
if [[ -z "$PROJECT_ROOT" ]]; then
    PROJECT_ROOT="$(pwd)"
fi

INPUT="${1:-}"

# Default: use the installed SDK
if [[ -z "$INPUT" ]]; then
    if [[ -d "$HOME/.nxuskit/sdk/current" ]]; then
        INPUT="$HOME/.nxuskit/sdk/current"
        echo "[setup-sdk] Using installed SDK: $INPUT"
    else
        echo "[setup-sdk] No SDK found. Install one first:" >&2
        echo "  Download a nxuskit-sdk archive, extract it, then source this script with the extracted SDK directory." >&2
        echo "  Example: source sdk-packaging/scripts/setup-sdk.sh /path/to/nxuskit-sdk-1.0.2-oss-<platform>" >&2
        [[ "${BASH_SOURCE[0]:-}" != "${0:-}" ]] && return 1
        exit 1
    fi
fi

# Resolve to absolute path
NXUSKIT_SDK_DIR="$(cd "$INPUT" && pwd)"

if [[ ! -d "$NXUSKIT_SDK_DIR/lib" ]]; then
    echo "[setup-sdk] ERROR: $NXUSKIT_SDK_DIR/lib not found — is this an SDK directory?" >&2
    [[ "${BASH_SOURCE[0]:-}" != "${0:-}" ]] && return 1
    exit 1
fi

# Export environment variables
export NXUSKIT_SDK_DIR
export NXUSKIT_LIB_DIR="${NXUSKIT_SDK_DIR}/lib"
export NXUSKIT_INCLUDE_DIR="${NXUSKIT_SDK_DIR}/include"

# Platform-specific library path
case "$(uname -s)" in
    Darwin)
        export DYLD_LIBRARY_PATH="${NXUSKIT_LIB_DIR}${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}"
        ;;
    *)
        export LD_LIBRARY_PATH="${NXUSKIT_LIB_DIR}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
        ;;
esac

# CGo flags for Go FFI providers
export CGO_LDFLAGS="${CGO_LDFLAGS:-} -L${NXUSKIT_LIB_DIR} -lnxuskit"
export CGO_CFLAGS="${CGO_CFLAGS:-} -I${NXUSKIT_INCLUDE_DIR}"

echo "[setup-sdk] NXUSKIT_SDK_DIR=${NXUSKIT_SDK_DIR}"
echo "[setup-sdk] NXUSKIT_LIB_DIR=${NXUSKIT_LIB_DIR}"

# Create packages/nxuskit symlink for Rust path deps
if [[ -f "${NXUSKIT_SDK_DIR}/rust/Cargo.toml" ]]; then
    mkdir -p "${PROJECT_ROOT}/packages"
    # Remove existing symlink or directory (but not a real packages/ with content)
    if [[ -L "${PROJECT_ROOT}/packages/nxuskit" ]]; then
        rm "${PROJECT_ROOT}/packages/nxuskit"
    elif [[ -d "${PROJECT_ROOT}/packages/nxuskit" ]]; then
        echo "[setup-sdk] WARNING: packages/nxuskit is a real directory, not replacing" >&2
    fi
    if [[ ! -e "${PROJECT_ROOT}/packages/nxuskit" ]]; then
        ln -s "${NXUSKIT_SDK_DIR}/rust" "${PROJECT_ROOT}/packages/nxuskit"
        echo "[setup-sdk] packages/nxuskit -> ${NXUSKIT_SDK_DIR}/rust"
    fi
else
    echo "[setup-sdk] WARNING: ${NXUSKIT_SDK_DIR}/rust/Cargo.toml not found" >&2
fi

# Create go.work for Go module resolution
if [[ -f "${NXUSKIT_SDK_DIR}/go/go.mod" ]]; then
    # Extract Go version from the SDK's go.mod
    GO_VER=$(grep "^go " "${NXUSKIT_SDK_DIR}/go/go.mod" | awk '{print $2}')
    GO_VER="${GO_VER:-1.24}"

    # Find all Go example modules in the project
    GO_MODULES=()
    while IFS= read -r moddir; do
        # Relative path from project root
        rel="${moddir#${PROJECT_ROOT}/}"
        GO_MODULES+=("$rel")
    done < <(find "${PROJECT_ROOT}/examples" -name "go.mod" -exec dirname {} \; 2>/dev/null | sort)

    if [[ ${#GO_MODULES[@]} -gt 0 ]]; then
        cat > "${PROJECT_ROOT}/go.work" <<GOWORK
// Generated by setup-sdk.sh — do not commit.
// Maps the nxuskit-go module to the installed SDK bundle.
go ${GO_VER}

use (
$(printf '    ./%s\n' "${GO_MODULES[@]}")
)

replace github.com/nxus-SYSTEMS/nxusKit/packages/nxuskit-go => ${NXUSKIT_SDK_DIR}/go
GOWORK
        echo "[setup-sdk] go.work -> ${#GO_MODULES[@]} modules, replace -> ${NXUSKIT_SDK_DIR}/go"
    else
        echo "[setup-sdk] Go SDK available at ${NXUSKIT_SDK_DIR}/go (no Go modules found in project)"
    fi
fi

# Show edition info
if [[ -f "${NXUSKIT_SDK_DIR}/capability-manifest.json" ]] && command -v python3 &>/dev/null; then
    EDITION=$(python3 -c "import json; print(json.load(open('${NXUSKIT_SDK_DIR}/capability-manifest.json'))['edition'])" 2>/dev/null || echo "unknown")
    VERSION=$(python3 -c "import json; print(json.load(open('${NXUSKIT_SDK_DIR}/capability-manifest.json'))['sdk_version'])" 2>/dev/null || echo "unknown")
    echo "[setup-sdk] Edition: ${EDITION}, Version: ${VERSION}"
fi

echo "[setup-sdk] Done. Add 'packages/' and 'go.work' to your .gitignore if not already there."
