/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#ifndef NXUSKIT_H
#define NXUSKIT_H

#include <stdint.h>
#include <stdbool.h>


/**
 * Opaque handle to an Evidence set.
 */
typedef struct NxuskitBnEvidence NxuskitBnEvidence;

/**
 * Opaque handle to a BayesianNetwork.
 */
typedef struct NxuskitBnNet NxuskitBnNet;

/**
 * Opaque handle to inference results (marginal distributions).
 */
typedef struct NxuskitBnResult NxuskitBnResult;

/**
 * Opaque handle wrapping a boxed provider trait object.
 * Consumers create via `nxuskit_create_provider` and free via `nxuskit_free_provider`.
 */
typedef struct NxuskitProvider NxuskitProvider;

/**
 * Opaque handle wrapping a JSON response string.
 * Consumers read via `nxuskit_response_json` and free via `nxuskit_free_response`.
 */
typedef struct NxuskitResponse NxuskitResponse;

/**
 * Opaque solver session handle for C ABI consumers.
 */
typedef struct NxuskitSolverSession NxuskitSolverSession;

/**
 * Opaque handle for an in-progress streaming session.
 * Supports cancellation and must be freed after the stream completes.
 */
typedef struct NxuskitStream NxuskitStream;

typedef int32_t (*NxuskitStreamCallback)(const char *chunk_json, void *user_data);

typedef void (*NxuskitStreamDoneCallback)(const char *final_json, void *user_data);

/**
 * Callback for each streaming inference chunk.
 * `chunk_json` is a NUL-terminated JSON string (valid for the duration of the call).
 * `iteration` is the current sample count, `total` is the target.
 * `is_final` is true for the last chunk.
 * Return `true` to continue, `false` to cancel.
 */
typedef bool (*NxuskitBnStreamCallback)(const char *chunk_json,
                                        uint32_t iteration,
                                        uint32_t total,
                                        bool is_final,
                                        void *user_data);

const char *nxuskit_version(void);

/**
 * Returns the ABI compatibility version as a static string.
 *
 * The returned pointer is to static memory and MUST NOT be freed.
 * Safe to call from any thread at any time. No initialization required.
 */
const char *nxuskit_abi_version(void);

/**
 * Returns the edition the binary was compiled for.
 *
 * One of: `"oss"`, `"pro"`, `"enterprise"`.
 * The returned pointer is to static memory and MUST NOT be freed.
 * Safe to call from any thread at any time. No initialization required.
 */
const char *nxuskit_edition(void);

/**
 * Returns a JSON string describing all compiled-in capabilities.
 *
 * Caller MUST free the returned pointer with `nxuskit_free_string()`.
 * Returns NULL on allocation failure (sets last error).
 * Safe to call from any thread. Each call allocates a fresh string.
 */
char *nxuskit_capabilities(void);

/**
 * Returns a JSON string with build fingerprint and signing key info.
 *
 * Includes: abi_version, sdk_version, edition, build_target, build_profile.
 * Caller MUST free the returned pointer with `nxuskit_free_string()`.
 * Returns NULL on allocation failure (sets last error).
 */
char *nxuskit_build_info(void);

/**
 * Returns entitlement information as a JSON string.
 *
 * If `license_key` is non-NULL, it is used to determine the effective edition
 * (compile-time edition upgraded by a valid license key).
 *
 * Caller MUST free the returned pointer with `nxuskit_free_string()`.
 * Returns NULL on allocation failure.
 *
 * # Safety
 *
 * `license_key` must be a valid NUL-terminated C string, or NULL.
 */
char *nxuskit_entitlement_info(const char *license_key);

/**
 * Resolve the active license token from all available sources.
 *
 * Resolution order:
 *   1. `NXUSKIT_LICENSE_TOKEN` environment variable
 *   2. `~/.nxuskit/license.token` file
 *   3. `explicit_key` parameter (if non-NULL)
 *
 * Returns JSON with resolution result. Caller MUST free with `nxuskit_free_string()`.
 * Returns NULL on allocation failure.
 *
 * # Safety
 *
 * `explicit_key` must be a valid NUL-terminated C string, or NULL.
 */
char *nxuskit_license_resolve(const char *explicit_key);

/**
 * Validate a license token JWT string.
 *
 * Performs RS384 signature verification, claim parsing, and type-specific
 * validation (expiry, machine binding, version ceiling).
 *
 * Returns JSON with validation result. Caller MUST free with `nxuskit_free_string()`.
 * Returns NULL on allocation failure.
 *
 * # Safety
 *
 * `token_jwt` must be a valid NUL-terminated C string.
 */
char *nxuskit_license_validate(const char *token_jwt);

/**
 * Get the machine fingerprint for this device.
 *
 * Returns `"sha256:<64-hex-chars>"` on success.
 * Returns NULL if machine ID cannot be determined (e.g., Docker container).
 * Caller MUST free with `nxuskit_free_string()`.
 */
char *nxuskit_license_machine_id(void);

/**
 * Activate a Pro license on this machine.
 *
 * Calls the licensing microservice to validate the purchase ID, generate
 * a machine-bound developer token, and store it at `~/.nxuskit/license.token`.
 *
 * # Safety
 *
 * `purchase_id` must be a valid NUL-terminated C string.
 */
char *nxuskit_license_activate(const char *purchase_id);

/**
 * Deactivate the Pro license on this machine.
 *
 * Calls the licensing microservice to release this machine's seat and
 * removes `~/.nxuskit/license.token`.
 */
char *nxuskit_license_deactivate(void);

/**
 * Issue a 30-day trial token for this machine.
 *
 * Calls the licensing microservice trial endpoint.
 */
char *nxuskit_license_trial_issue(void);

/**
 * Activate a trial token (complete email verification).
 *
 * # Safety
 *
 * `activation_code` must be a valid NUL-terminated C string.
 */
char *nxuskit_license_trial_activate(const char *activation_code);

/**
 * Store a credential for a provider in the OS credential store.
 *
 * Returns 0 on success, non-zero on failure (sets last error).
 * Falls back to file-based storage if OS store is unavailable.
 */
int32_t nxuskit_auth_set_credential(const char *provider_id, const char *api_key);

/**
 * Remove a stored credential for a provider.
 *
 * Returns 0 on success, non-zero if no credential existed.
 */
int32_t nxuskit_auth_remove_credential(const char *provider_id);

/**
 * Resolve a credential for a provider using deterministic precedence.
 *
 * Returns JSON: `{"provider_id":"...","source":"...","has_credential":bool}`
 * Caller MUST free the returned pointer with `nxuskit_free_string()`.
 */
char *nxuskit_auth_resolve(const char *provider_id, const char *explicit_key);

/**
 * Get auth status for a single provider.
 *
 * Returns JSON with status, masked preview, source, dashboard URL.
 * Caller MUST free the returned pointer with `nxuskit_free_string()`.
 */
char *nxuskit_auth_status(const char *provider_id);

/**
 * Get auth status for all known providers.
 *
 * Returns JSON array. Caller MUST free with `nxuskit_free_string()`.
 */
char *nxuskit_auth_status_all(void);

/**
 * Get metadata for all known providers.
 *
 * Returns JSON array. Caller MUST free with `nxuskit_free_string()`.
 */
char *nxuskit_auth_providers(void);

struct NxuskitProvider *nxuskit_create_provider(const char *config_json);

void nxuskit_free_provider(struct NxuskitProvider *provider);

struct NxuskitResponse *nxuskit_chat(struct NxuskitProvider *provider, const char *request_json);

const char *nxuskit_response_json(const struct NxuskitResponse *response);

void nxuskit_free_response(struct NxuskitResponse *response);

struct NxuskitStream *nxuskit_chat_stream(struct NxuskitProvider *provider,
                                          const char *request_json,
                                          NxuskitStreamCallback on_chunk,
                                          NxuskitStreamDoneCallback on_done,
                                          void *user_data);

void nxuskit_cancel_stream(struct NxuskitStream *stream);

void nxuskit_free_stream(struct NxuskitStream *stream);

char *nxuskit_list_models(struct NxuskitProvider *provider);

/**
 * One-shot completion convenience function.
 *
 * Auto-detects provider from model name and environment variables.
 * Returns response text as a JSON string `{"content":"...","model":"..."}`.
 * Caller MUST free the returned pointer with `nxuskit_free_string()`.
 *
 * `config_json` is a JSON object:
 *   `{"model": "gpt-4o", "prompt": "Hello", "temperature": 0.7, "max_tokens": 1024}`
 *
 * Only `model` and `prompt` are required.
 *
 * Returns NULL on error (check `nxuskit_last_error()`).
 *
 * # Safety
 * `config_json` must be a valid, NUL-terminated C string.
 */
char *nxuskit_completion(const char *config_json);

/**
 * Streaming completion convenience function.
 *
 * Auto-detects provider from model name and environment variables.
 * Calls `on_chunk` for each streaming chunk, `on_done` when complete.
 *
 * `config_json` is a JSON object:
 *   `{"model": "gpt-4o", "prompt": "Hello", "temperature": 0.7, "max_tokens": 1024}`
 *
 * Only `model` and `prompt` are required.
 *
 * Returns a stream handle (free with `nxuskit_free_stream()`), or NULL on error.
 *
 * # Safety
 * `config_json` must be a valid, NUL-terminated C string.
 * Callback function pointers must remain valid until `on_done` fires.
 * `user_data` is forwarded opaquely to callbacks.
 */
struct NxuskitStream *nxuskit_completion_stream(const char *config_json,
                                                NxuskitStreamCallback on_chunk,
                                                NxuskitStreamDoneCallback on_done,
                                                void *user_data);

/**
 * Load plugins from a directory.
 *
 * Scans the directory for `*.json` manifest files paired with shared libraries,
 * verifies ABI compatibility and signatures, loads valid plugins into the registry.
 * Returns the number of successfully loaded plugins, or -1 on argument error.
 *
 * Plugin load failures are non-fatal — rejected plugins are logged via `log::warn!`.
 * The string pointed to by `dir_path` is borrowed only for the duration of the call.
 *
 * # Safety
 * `dir_path` must be a valid, NUL-terminated C string.
 */
int32_t nxuskit_plugin_load_dir(const char *dir_path);

/**
 * Return a JSON array describing all loaded plugins.
 *
 * Caller MUST free the returned pointer with `nxuskit_free_string()`.
 * Returns `"[]"` if no plugins are loaded.
 * Returns NULL on internal error (sets last error).
 */
char *nxuskit_plugin_list(void);

/**
 * Return JSON metadata for a specific plugin by name.
 *
 * Caller MUST free the returned pointer with `nxuskit_free_string()`.
 * Returns NULL if the plugin is not found (sets last error).
 *
 * # Safety
 * `name` must be a valid, NUL-terminated C string.
 */
char *nxuskit_plugin_info(const char *name);

/**
 * Return the number of loaded plugins.
 *
 * Always succeeds. Returns 0 if no plugins are loaded.
 */
int32_t nxuskit_plugin_count(void);

/**
 * Check if a specific plugin is loaded by name.
 *
 * Returns 1 if loaded, 0 if not loaded or on error.
 *
 * # Safety
 * `name` must be a valid, NUL-terminated C string.
 */
int32_t nxuskit_plugin_loaded(const char *name);

/**
 * Unload all plugins, drop library handles, and clear the registry.
 *
 * Safe to call even if no plugins are loaded.
 */
void nxuskit_plugin_unload_all(void);

/**
 * Set the plugin trust mode.
 *
 * # Arguments
 * * `mode` — 0 = SignedOnly (default), 1 = AllowUnsigned
 *
 * Returns 0 on success, -1 on invalid mode.
 */
int32_t nxuskit_plugin_set_trust_mode(int32_t mode);

/**
 * Get the current plugin trust mode.
 *
 * Returns 0 = SignedOnly, 1 = AllowUnsigned.
 */
int32_t nxuskit_plugin_get_trust_mode(void);

/**
 * Load plugins from a directory with explicit trust mode awareness.
 *
 * Equivalent to `nxuskit_plugin_load_dir` but documents that the current
 * trust mode setting is respected during loading.
 */
int32_t nxuskit_plugin_load_dir_trusted(const char *dir_path);

/**
 * Start an OAuth authentication flow for a provider.
 *
 * This is a BLOCKING call — it launches a browser, starts a localhost
 * callback server, and waits for the authorization code.
 *
 * provider_id: Provider to authenticate (e.g., "azure-openai").
 * timeout_secs: Max seconds to wait for callback (0 = default 120s).
 *
 * Returns JSON: {"success": true|false, "provider_id": "...",
 *                "message": "...", "error": null|"message"}
 */
char *nxuskit_oauth_start(const char *provider_id, uint32_t timeout_secs);

/**
 * Check OAuth token status for a provider.
 *
 * Returns JSON: {"authenticated": true|false, "provider_id": "...",
 *                "expires_at": null, "scopes": null}
 */
char *nxuskit_oauth_status(const char *provider_id);

/**
 * Remove the stored OAuth token for a provider.
 *
 * Returns 0 on success (or if no token was stored), -1 on error.
 */
int32_t nxuskit_oauth_revoke(const char *provider_id);

const char *nxuskit_last_error(void);

void nxuskit_free_string(char *ptr);

/**
 * Create an empty BayesianNetwork.
 */
struct NxuskitBnNet *nxuskit_bn_net_create(void);

/**
 * Destroy a BayesianNetwork handle.
 */
void nxuskit_bn_net_destroy(struct NxuskitBnNet *net);

/**
 * Load a BIF file into a new BayesianNetwork. Returns NULL on error.
 */
struct NxuskitBnNet *nxuskit_bn_net_load_file(const char *path);

/**
 * Get the number of variables in the network.
 */
int32_t nxuskit_bn_net_num_variables(const struct NxuskitBnNet *net);

/**
 * Get all variable names as a JSON array string. Caller must free with nxuskit_free_string.
 */
char *nxuskit_bn_net_variables(const struct NxuskitBnNet *net);

/**
 * Get states for a variable as a JSON array. Caller must free with nxuskit_free_string.
 */
char *nxuskit_bn_net_variable_states(const struct NxuskitBnNet *net, const char *variable);

/**
 * Create an empty Evidence set.
 */
struct NxuskitBnEvidence *nxuskit_bn_ev_create(void);

/**
 * Destroy an Evidence handle.
 */
void nxuskit_bn_ev_destroy(struct NxuskitBnEvidence *ev);

/**
 * Set a discrete observation: variable=state. Requires network for validation.
 */
bool nxuskit_bn_ev_set_discrete(struct NxuskitBnEvidence *ev,
                                const struct NxuskitBnNet *net,
                                const char *variable,
                                const char *state);

/**
 * Retract evidence for a variable.
 */
bool nxuskit_bn_ev_retract(struct NxuskitBnEvidence *ev, const char *variable);

/**
 * Clear all evidence.
 */
bool nxuskit_bn_ev_clear(struct NxuskitBnEvidence *ev);

/**
 * Run inference. `algorithm` is "ve", "jt", or "gibbs". Returns NULL on error.
 * For Gibbs: `num_samples` and `burn_in` control sampling (0 = default 10000/1000).
 * `seed` of 0 means non-deterministic.
 */
struct NxuskitBnResult *nxuskit_bn_infer(const struct NxuskitBnNet *net,
                                         const struct NxuskitBnEvidence *ev,
                                         const char *algorithm,
                                         uint32_t num_samples,
                                         uint32_t burn_in,
                                         uint64_t seed);

/**
 * Destroy a result handle.
 */
void nxuskit_bn_result_destroy(struct NxuskitBnResult *result);

/**
 * Get full result as JSON. Caller must free with nxuskit_free_string.
 */
char *nxuskit_bn_result_json(const struct NxuskitBnResult *result);

/**
 * Query a single variable's posterior. Returns JSON object {state: probability}.
 * Caller must free with nxuskit_free_string.
 */
char *nxuskit_bn_result_query(const struct NxuskitBnResult *result, const char *variable);

/**
 * Get the number of variables in the result.
 */
int32_t nxuskit_bn_result_num_variables(const struct NxuskitBnResult *result);

/**
 * Iterate: get the next variable name. Returns NULL when done.
 * Caller must free with nxuskit_free_string.
 */
char *nxuskit_bn_result_next(struct NxuskitBnResult *result);

/**
 * Reset the iteration cursor to the beginning.
 */
void nxuskit_bn_result_reset(struct NxuskitBnResult *result);

/**
 * Save a BayesianNetwork to a BIF file. Returns true on success.
 */
bool nxuskit_bn_net_save_file(const struct NxuskitBnNet *net, const char *path);

/**
 * Set a continuous observation for a Gaussian variable.
 */
bool nxuskit_bn_ev_set_continuous(struct NxuskitBnEvidence *ev,
                                  const struct NxuskitBnNet *net,
                                  const char *variable,
                                  double value);

/**
 * Add a Gaussian variable to the network.
 */
bool nxuskit_bn_net_add_gaussian_variable(struct NxuskitBnNet *net,
                                          const char *name,
                                          double mean_base,
                                          double variance);

/**
 * Set a parent weight for a Gaussian variable's conditional distribution.
 */
bool nxuskit_bn_net_set_gaussian_weight(struct NxuskitBnNet *net,
                                        const char *variable,
                                        const char *parent,
                                        double weight);

/**
 * Get the posterior mean for a continuous variable. Returns NaN on error.
 */
double nxuskit_bn_result_mean(const struct NxuskitBnResult *result, const char *variable);

/**
 * Get the posterior variance for a continuous variable. Returns NaN on error.
 */
double nxuskit_bn_result_variance(const struct NxuskitBnResult *result, const char *variable);

/**
 * Get the full continuous marginal as JSON: {"mean": ..., "variance": ..., "ci_lower": ..., "ci_upper": ...}.
 * Caller must free with nxuskit_free_string. Returns NULL on error.
 */
char *nxuskit_bn_result_continuous_marginal(const struct NxuskitBnResult *result,
                                            const char *variable);

/**
 * Run inference with a JSON configuration object for algorithm-specific parameters.
 *
 * `algorithm`: "ve", "jt", "gibbs", "lbp", "nuts", "hmc", "gaussian".
 * `config_json`: JSON string with algorithm-specific parameters. NULL for defaults.
 *
 * VE config: {"elimination_heuristic": "min_fill"} or {"elimination_heuristic": "min_weight"}
 * LBP config: {"max_iterations": 100, "convergence_threshold": 1e-4, "damping_factor": 0.5}
 * NUTS config: {"num_samples": 1000, "num_warmup": 500, "max_tree_depth": 10, "seed": 42, "num_chains": 4}
 * Gibbs config: {"num_samples": 10000, "burn_in": 1000, "seed": 42}
 */
struct NxuskitBnResult *nxuskit_bn_infer_with_config(const struct NxuskitBnNet *net,
                                                     const struct NxuskitBnEvidence *ev,
                                                     const char *algorithm,
                                                     const char *config_json);

/**
 * Run streaming Gibbs inference with callback-based delivery.
 *
 * Calls `on_chunk` for each progressive inference result. The chunk JSON has the
 * same format as `nxuskit_bn_result_json` plus `iteration`, `total_iterations`,
 * `convergence_metric`, and `is_final` fields.
 *
 * Returns `true` on success (all chunks delivered or cancelled by callback).
 * Returns `false` on error (check `nxuskit_last_error`).
 *
 * `chunk_size` controls how many Gibbs samples between callbacks (0 = default 1000).
 */
bool nxuskit_bn_infer_stream(const struct NxuskitBnNet *net,
                             const struct NxuskitBnEvidence *ev,
                             uint32_t num_samples,
                             uint32_t burn_in,
                             uint64_t seed,
                             uint32_t chunk_size,
                             NxuskitBnStreamCallback on_chunk,
                             void *user_data);

/**
 * Learn CPT parameters from a CSV dataset using Maximum Likelihood Estimation.
 *
 * Loads the CSV at `csv_path`, fits CPTs on the network using MLE with
 * Laplace smoothing (`pseudocount`; 0.0 = no smoothing, 1.0 = default).
 * The network is modified in-place with learned parameters.
 *
 * Returns `true` on success, `false` on error (check `nxuskit_last_error`).
 */
bool nxuskit_bn_learn_mle(struct NxuskitBnNet *net, const char *csv_path, double pseudocount);

/**
 * Compute log-likelihood of data given the current network CPTs.
 *
 * Returns the log-likelihood value, or `f64::NEG_INFINITY` on error.
 */
double nxuskit_bn_log_likelihood(const struct NxuskitBnNet *net, const char *csv_path);

/**
 * Run structure learning on a network given CSV data.
 *
 * `algorithm`: "hill_climb" or "k2".
 * `scoring`: "bic" or "bdeu".
 * `csv_path`: path to CSV data file.
 * `max_parents`: maximum parents per node (0 = default: 5 for hill_climb, 3 for k2).
 * `max_steps`: maximum search steps for hill_climb (0 = default 1000). Ignored for k2.
 * `ess`: equivalent sample size for BDeu (0.0 = default 10.0). Ignored for BIC.
 * `ordering_json`: JSON array of variable names for K2 ordering. NULL for hill_climb.
 *
 * Returns a JSON string with the search results (edges, score, iterations).
 * Caller must free with `nxuskit_free_string`. Returns NULL on error.
 */
char *nxuskit_bn_search_structure(const struct NxuskitBnNet *net,
                                  const char *csv_path,
                                  const char *algorithm,
                                  const char *scoring,
                                  uint32_t max_parents,
                                  uint32_t max_steps,
                                  double ess,
                                  const char *ordering_json);

/**
 * Create a new isolated CLIPS session.
 * Returns session handle (>0) or 0 on error.
 */
uint64_t nxuskit_clips_session_create(void);

/**
 * Destroy a session and free resources. Invalidates the handle.
 */
void nxuskit_clips_session_destroy(uint64_t session);

/**
 * Reset session: retract all facts, restore initial state, preserve rules.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_reset(uint64_t session);

/**
 * Clear session: remove all constructs (rules, templates, facts, modules).
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_clear(uint64_t session);

/**
 * Get session metadata as JSON string. Caller frees with `nxuskit_free_string`.
 * Returns NULL on error.
 */
char *nxuskit_clips_session_info(uint64_t session);

/**
 * Load CLIPS constructs from a .clp file.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_load_file(uint64_t session, const char *path);

/**
 * Load CLIPS constructs from a string.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_load_string(uint64_t session, const char *constructs);

/**
 * Load pre-compiled binary constructs from a file.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_load_binary(uint64_t _session, const char *path);

/**
 * Save compiled constructs to a binary file.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_save_binary(uint64_t _session, const char *path);

/**
 * Build a single CLIPS construct from a string.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_build(uint64_t session, const char *construct);

/**
 * Execute a CLIPS batch file.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_batch(uint64_t _session, const char *path);

/**
 * Assert a fact from a CLIPS string. Returns fact index or -1 on error.
 */
int64_t nxuskit_clips_fact_assert_string(uint64_t session, const char *fact_string);

/**
 * Assert a structured fact. Returns fact index or -1 on error.
 * `slots_json` is a JSON object mapping slot names to type-tagged values.
 */
int64_t nxuskit_clips_fact_assert_structured(uint64_t session,
                                             const char *template_name,
                                             const char *slots_json);

/**
 * Retract a fact by index. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_fact_retract(uint64_t session, int64_t fact_index);

/**
 * Retract all facts of a template. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_fact_retract_by_template(uint64_t session, const char *template_name);

/**
 * Check if a fact exists. Returns true if it does.
 * On error (invalid session), returns false; check nxuskit_last_error().
 */
bool nxuskit_clips_fact_exists(uint64_t session, int64_t fact_index);

/**
 * Get a single slot value as type-tagged JSON. Caller frees.
 * Returns NULL on error.
 */
char *nxuskit_clips_fact_get_slot(uint64_t session, int64_t fact_index, const char *slot_name);

/**
 * Get all slot values as JSON object. Caller frees.
 * Returns NULL on error.
 */
char *nxuskit_clips_fact_slot_values(uint64_t session, int64_t fact_index);

/**
 * Get pretty-print form of a fact. Caller frees.
 * Returns NULL on error.
 */
char *nxuskit_clips_fact_pp_form(uint64_t session, int64_t fact_index);

/**
 * Get fact index (identity operation, useful after iteration).
 */
int64_t nxuskit_clips_fact_index(uint64_t session, int64_t fact_index);

/**
 * Get all fact indices as JSON array. Caller frees.
 * Returns NULL on error.
 */
char *nxuskit_clips_facts_list(uint64_t session);

/**
 * Get facts by template as JSON array of indices. Caller frees.
 * Returns NULL on error.
 */
char *nxuskit_clips_facts_by_template(uint64_t session, const char *template_name);

/**
 * Check if a template exists. Returns true/false.
 */
bool nxuskit_clips_template_exists(uint64_t session, const char *name);

/**
 * Get list of all template names as JSON array. Caller frees.
 */
char *nxuskit_clips_template_list(uint64_t session);

/**
 * Get slot names for a template as JSON array. Caller frees.
 */
char *nxuskit_clips_template_slot_names(uint64_t session, const char *template_name);

/**
 * Get slot info for a template as JSON array. Caller frees.
 */
char *nxuskit_clips_template_slot_info(uint64_t session, const char *template_name);

/**
 * Get facts for a template as JSON array of indices. Caller frees.
 */
char *nxuskit_clips_template_facts(uint64_t session, const char *template_name);

/**
 * Get pretty-print form of a template. Caller frees.
 */
char *nxuskit_clips_template_pp_form(uint64_t session, const char *template_name);

/**
 * Run inference. limit = -1 for no limit. Returns rules fired or -1 on error.
 */
int64_t nxuskit_clips_session_run(uint64_t session, int64_t limit);

/**
 * Halt a running inference from another thread.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_halt(uint64_t session);

/**
 * Get agenda size. Returns count or -1 on error.
 */
int64_t nxuskit_clips_agenda_size(uint64_t session);

/**
 * Clear the agenda. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_agenda_clear(uint64_t session);

/**
 * Reorder the agenda. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_agenda_reorder(uint64_t _session);

/**
 * Get current conflict resolution strategy. Caller frees.
 */
char *nxuskit_clips_strategy_get(uint64_t session);

/**
 * Set conflict resolution strategy. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_strategy_set(uint64_t session, const char *strategy);

/**
 * Get salience evaluation mode. Caller frees.
 */
char *nxuskit_clips_salience_mode_get(uint64_t _session);

/**
 * Set salience evaluation mode. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_salience_mode_set(uint64_t _session, const char *mode);

/**
 * Check if a rule exists.
 */
bool nxuskit_clips_rule_exists(uint64_t session, const char *name);

/**
 * Get list of all rule names as JSON array. Caller frees.
 */
char *nxuskit_clips_rule_list(uint64_t session);

/**
 * Get number of times a rule has fired. Returns count or -1 on error.
 */
int64_t nxuskit_clips_rule_times_fired(uint64_t session, const char *rule_name);

/**
 * Set a breakpoint on a rule. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_rule_breakpoint_set(uint64_t session, const char *rule_name);

/**
 * Remove a breakpoint from a rule. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_rule_breakpoint_remove(uint64_t session, const char *rule_name);

/**
 * Check if a rule has a breakpoint.
 */
bool nxuskit_clips_rule_has_breakpoint(uint64_t session, const char *rule_name);

/**
 * Refresh a rule's activations. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_rule_refresh(uint64_t _session, const char *rule_name);

/**
 * Get pretty-print form of a rule. Caller frees.
 */
char *nxuskit_clips_rule_pp_form(uint64_t session, const char *rule_name);

/**
 * Delete a rule. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_rule_delete(uint64_t _session, const char *rule_name);

/**
 * Get fact duplication setting.
 */
bool nxuskit_clips_fact_duplication_get(uint64_t session);

/**
 * Set fact duplication setting. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_fact_duplication_set(uint64_t session, bool allow);

/**
 * Get reset globals setting.
 */
bool nxuskit_clips_reset_globals_get(uint64_t _session);

/**
 * Set reset globals setting. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_reset_globals_set(uint64_t _session, bool reset);

/**
 * Evaluate a CLIPS expression. Returns type-tagged JSON. Caller frees.
 */
char *nxuskit_clips_eval(uint64_t session, const char *expression);

/**
 * Call a CLIPS function by name with JSON arguments. Returns type-tagged JSON. Caller frees.
 */
char *nxuskit_clips_function_call(uint64_t session,
                                  const char *function_name,
                                  const char *args_json);

/**
 * Load constructs from a JSON definition.
 *
 * The JSON format supports:
 * ```json
 * {
 *   "modules": [{"name": "mod-name"}],
 *   "templates": [{"name": "t", "slots": [{"name": "s", "type": "INTEGER"}]}],
 *   "rules": [{"name": "r", "source": "(defrule r ...)"}],
 *   "facts": ["(t (s 1))"]
 * }
 * ```
 *
 * Processing order: modules → templates → rules → facts.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_load_json(uint64_t session, const char *json);

/**
 * Preload a named session with rules configuration.
 * The rules_json is stored and SHA-256 hashed for deduplication.
 * Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_session_preload(const char *name, const char *rules_json);

/**
 * Retrieve a clone of a cached session. Creates a new independent session
 * pre-loaded with the cached rules. Returns session handle or 0 on error.
 */
uint64_t nxuskit_clips_session_get_cached(const char *name);

/**
 * Remove a cached session by name.
 * Returns 0 on success, -1 if not found.
 */
int32_t nxuskit_clips_session_cache_remove(const char *name);

/**
 * Check whether a defmodule exists.
 */
bool nxuskit_clips_module_exists(uint64_t session, const char *name);

/**
 * List all defmodule names. Returns JSON array. Caller frees.
 */
char *nxuskit_clips_module_list(uint64_t session);

/**
 * Get the current module name. Returns allocated string. Caller frees.
 */
char *nxuskit_clips_module_current_get(uint64_t session);

/**
 * Set the current module. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_module_current_set(uint64_t session, const char *name);

/**
 * Push a module onto the focus stack.
 */
int32_t nxuskit_clips_focus_push(uint64_t session, const char *module_name);

/**
 * Get the module at the top of the focus stack. Returns module name or NULL.
 * Caller frees.
 */
char *nxuskit_clips_focus_get(uint64_t session);

/**
 * Pop the top module from the focus stack. Returns 0 or -1 if stack empty.
 */
int32_t nxuskit_clips_focus_pop(uint64_t session);

/**
 * Clear the entire focus stack. Returns 0 on success.
 */
int32_t nxuskit_clips_focus_clear(uint64_t session);

/**
 * Check if a global variable exists.
 */
bool nxuskit_clips_global_exists(uint64_t session, const char *name);

/**
 * Return all global variable names as a JSON array. Caller frees.
 */
char *nxuskit_clips_global_list(uint64_t session);

/**
 * Get the value of a global variable as JSON. Caller frees.
 */
char *nxuskit_clips_global_get_value(uint64_t session, const char *name);

/**
 * Set the value of a global variable from a JSON value. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_global_set_value(uint64_t session, const char *name, const char *value_json);

/**
 * Enable watching for the specified item. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_watch(uint64_t session, const char *item);

/**
 * Disable watching for the specified item. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_unwatch(uint64_t session, const char *item);

/**
 * Start recording all CLIPS output to a file. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_dribble_on(uint64_t session, const char *path);

/**
 * Stop recording CLIPS output. Returns 0 on success, -1 on error.
 */
int32_t nxuskit_clips_dribble_off(uint64_t session);

/**
 * Create a new solver session.
 *
 * `config_json` may be NULL for default configuration, or a JSON string
 * with optional fields: `timeout_ms`, `random_seed`, `max_conflicts`.
 *
 * Returns an opaque handle, or NULL on error (check `nxuskit_last_error()`).
 *
 * # Safety
 *
 * If non-null, `config_json` must point to a valid, NUL-terminated C string.
 */
struct NxuskitSolverSession *nxuskit_solver_session_create(const char *config_json);

/**
 * Destroy a solver session and free its memory.
 *
 * NULL is a no-op (safe to call with NULL).
 *
 * # Safety
 *
 * `session` must be NULL or a valid pointer previously returned by
 * `nxuskit_solver_session_create`. Must not be called more than once
 * for the same handle.
 */
void nxuskit_solver_session_destroy(struct NxuskitSolverSession *session);

/**
 * Add variables to the session.
 *
 * `variables_json` is a JSON array of variable definitions.
 * Returns true on success, false on error.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * `variables_json` must point to a valid, NUL-terminated C string.
 */
bool nxuskit_solver_add_variables(struct NxuskitSolverSession *session, const char *variables_json);

/**
 * Add constraints to the session.
 *
 * `constraints_json` is a JSON array of constraint definitions.
 * Returns true on success, false on error.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * `constraints_json` must point to a valid, NUL-terminated C string.
 */
bool nxuskit_solver_add_constraints(struct NxuskitSolverSession *session,
                                    const char *constraints_json);

/**
 * Set the optimization objective.
 *
 * `objective_json` is a JSON object with direction, expression, and
 * optional variable fields. Returns true on success, false on error.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * `objective_json` must point to a valid, NUL-terminated C string.
 */
bool nxuskit_solver_set_objective(struct NxuskitSolverSession *session, const char *objective_json);

/**
 * Retract (remove) constraints by name.
 *
 * `names_json` is a JSON array of strings. Returns true on success.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * `names_json` must point to a valid, NUL-terminated C string.
 */
bool nxuskit_solver_retract(struct NxuskitSolverSession *session, const char *names_json);

/**
 * Push a scope checkpoint.
 *
 * Returns true on success, false on error.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 */
bool nxuskit_solver_push(struct NxuskitSolverSession *session);

/**
 * Pop a scope checkpoint, restoring state.
 *
 * Returns true on success, false if stack is empty.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 */
bool nxuskit_solver_pop(struct NxuskitSolverSession *session);

/**
 * Solve the accumulated model.
 *
 * `config_json` may be NULL for session defaults, or a JSON config override.
 * Returns a JSON string (caller must free with `nxuskit_free_string`),
 * or NULL on error.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * If non-null, `config_json` must point to a valid, NUL-terminated C string.
 * The caller must free the returned string with `nxuskit_free_string`.
 */
char *nxuskit_solver_solve(struct NxuskitSolverSession *session, const char *config_json);

/**
 * Solve with streaming progress callback.
 *
 * For optimization problems (sessions with objectives), this uses iterative
 * constraint tightening to emit incremental progress events via `on_chunk`.
 * Each progress event is a JSON-serialized [`SolverProgressEvent`] with the
 * best-so-far objective value.
 *
 * For satisfaction problems (no objectives) or when `on_chunk` is NULL,
 * this delegates to synchronous solve with no intermediate events.
 *
 * The `on_chunk` callback returns `0` to continue solving or non-zero to
 * cancel. The `on_done` callback receives the final result JSON.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * If non-null, `config_json` must point to a valid, NUL-terminated C string.
 * Callback function pointers (`on_chunk`, `on_done`) must be valid for the
 * duration of this call. `user_data` is forwarded opaquely to callbacks.
 */
bool nxuskit_solver_solve_stream(struct NxuskitSolverSession *session,
                                 const char *config_json,
                                 int32_t (*on_chunk)(const char*, void*),
                                 void (*on_done)(const char*, void*),
                                 void *user_data);

/**
 * Reset the session, clearing all state.
 *
 * Returns true on success.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 */
bool nxuskit_solver_reset(struct NxuskitSolverSession *session);

/**
 * Return current variables as a JSON string.
 *
 * Caller must free the returned string with `nxuskit_free_string`.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * The caller must free the returned string with `nxuskit_free_string`.
 */
char *nxuskit_solver_variables(struct NxuskitSolverSession *session);

/**
 * Return current constraints as a JSON string.
 *
 * Caller must free the returned string with `nxuskit_free_string`.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * The caller must free the returned string with `nxuskit_free_string`.
 */
char *nxuskit_solver_constraints(struct NxuskitSolverSession *session);

/**
 * Return session status as a JSON string.
 *
 * Caller must free the returned string with `nxuskit_free_string`.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * The caller must free the returned string with `nxuskit_free_string`.
 */
char *nxuskit_solver_status(struct NxuskitSolverSession *session);

/**
 * Return solver capabilities as a JSON string.
 *
 * Caller must free the returned string with `nxuskit_free_string`.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * The caller must free the returned string with `nxuskit_free_string`.
 */
char *nxuskit_solver_capabilities(struct NxuskitSolverSession *session);

/**
 * Return the number of variables in the session.
 *
 * Returns -1 if session is NULL.
 *
 * # Safety
 *
 * `session` must be NULL or a valid pointer returned by `nxuskit_solver_session_create`.
 */
int64_t nxuskit_solver_num_variables(struct NxuskitSolverSession *session);

/**
 * Return the number of constraints in the session.
 *
 * Returns -1 if session is NULL.
 *
 * # Safety
 *
 * `session` must be NULL or a valid pointer returned by `nxuskit_solver_session_create`.
 */
int64_t nxuskit_solver_num_constraints(struct NxuskitSolverSession *session);

/**
 * Add an objective to the multi-objective list.
 *
 * `objective_json` is a JSON string describing an `ObjectiveDef`.
 * Returns true on success.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * `objective_json` must point to a valid, NUL-terminated C string.
 */
bool nxuskit_solver_add_objective(struct NxuskitSolverSession *session, const char *objective_json);

/**
 * Remove a named objective from the multi-objective list.
 *
 * `name` is a C string with the objective name. Returns true if found and removed.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * `name` must point to a valid, NUL-terminated C string.
 */
bool nxuskit_solver_retract_objective(struct NxuskitSolverSession *session, const char *name);

/**
 * Get the current objectives list as a JSON array.
 *
 * Returns a JSON string (caller must free with `nxuskit_free_string()`),
 * or NULL on error.
 *
 * # Safety
 *
 * `session` must be NULL or a valid pointer returned by `nxuskit_solver_session_create`.
 * The caller must free the returned string with `nxuskit_free_string`.
 */
char *nxuskit_solver_objectives(struct NxuskitSolverSession *session);

/**
 * Get the explanation artifacts from the last solve.
 *
 * Returns a JSON string representing the explanation (caller must free
 * with `nxuskit_free_string()`), or NULL if no explanation available.
 *
 * # Safety
 *
 * `session` must be NULL or a valid pointer returned by `nxuskit_solver_session_create`.
 * The caller must free the returned string with `nxuskit_free_string`.
 */
char *nxuskit_solver_explanation(struct NxuskitSolverSession *session);

/**
 * Add temporary assumptions for the next solve call.
 *
 * `assumptions_json` is a JSON array of constraint definitions.
 * Assumptions are auto-retracted after solve completes.
 * Returns true on success.
 *
 * # Safety
 *
 * `session` must be a valid pointer returned by `nxuskit_solver_session_create`.
 * `assumptions_json` must point to a valid, NUL-terminated C string.
 */
bool nxuskit_solver_add_assumptions(struct NxuskitSolverSession *session,
                                    const char *assumptions_json);

/**
 * Evaluate a ZEN Pro decision model against structured input.
 *
 * Stateless evaluation — no session or lifecycle management needed.
 * Function nodes (JavaScript) in the model are rejected with an error.
 *
 * Returns a JSON string on success (caller must free with
 * `nxuskit_zen_free_result`), or NULL on error (check `nxuskit_last_error()`).
 *
 * When the `provider-zen` feature is not compiled in, returns NULL and sets
 * last error to `{"error_type":"feature_unavailable","message":"zen"}`.
 *
 * # Safety
 *
 * Both `model_json` and `input_json` must be valid, NUL-terminated C strings.
 * The returned pointer must be freed with `nxuskit_zen_free_result`.
 */
char *nxuskit_zen_evaluate(const char *model_json, const char *input_json);

/**
 * Free a result string returned by `nxuskit_zen_evaluate`.
 *
 * NULL is a safe no-op.
 *
 * When the `provider-zen` feature is not compiled in, this is a no-op
 * (stubs never allocate result strings).
 *
 * # Safety
 *
 * `result` must be a pointer previously returned by `nxuskit_zen_evaluate`,
 * or NULL.
 */
void nxuskit_zen_free_result(char *result);

#endif  /* NXUSKIT_H */


